Assigment1
Sunzi2598/Sunzi-Bistro pull request #1
Opened 2021-04-12 07:26 UTC by Sunzi2598

2021-04-12 07:37 UTC, AdrianFlorian requested changes
Nice job Alexandra, 👏, just some overall comments:
- be careful on the method naming and comments
- keep the code as clean as possible, without any commented out code (even if you think you might need it)
- please rename the pull request name and description to reflect the actual changes

2021-04-12 07:37 UTC, AdrianFlorian commented on buttonAdd.js
> +  console.warn("added", { data });
Never commit with console logs :-), those are for you to see while developing, but they should never go to master :-)

2021-04-12 07:37 UTC, AdrianFlorian commented on buttonAdd.js
> +  //saving to localStorage
whenever you feel the need to add a comment above a block of code, it means that you should put it in a new method/function. A good code should be self documented and should not need comments :-) - in this example I would create a new method `saveToLocalStorage` and call it - makes it pretty self explanatory, right?

2021-04-12 07:37 UTC, AdrianFlorian commented on buttonAdd.js
> +// function addToTable() {
If you don't need it, remove it :-)

2021-04-12 07:37 UTC, AdrianFlorian commented on buttonAdd.js
> +function addToTable() {
Add what to table? Remember the comment above, the method names should be very clear :-)

2021-04-12 07:37 UTC, AdrianFlorian commented on imageHover.js
> +  x.style.height = "250px";
Method names should signify if they are altering the state of an object or if they are just returning an object. In this case, those 2 methods are altering the height and width of the image and it should be clear, something like `makeImageBig` or `applyBigImageStyling`. Also do not use variable names like `x` use a self explanatory name instead, like `image`

2021-04-12 09:39 UTC, chioreandan requested changes
Good Job @Sunzi2598,
Take more care when naming classes and methods and try to use less comments.

2021-04-12 09:39 UTC, chioreandan commented on buttonAdd.js
> +  ev.preventDefault(); //to stop the form submitting
No need for this kind of comments, it should be clear from the code :D

2021-04-12 09:39 UTC, chioreandan commented on buttonAdd.js
> +  ev.preventDefault(); //to stop the form submitting
I know that the teachers say that it is a good practice to add comments but in real life, it is not. The code naming of classes, methods, etc should make the code readable and easy to understand.

2021-04-12 09:39 UTC, chioreandan commented on index.html
> +            <img class="image" onmouseover="bigImg(this)" onmouseout="normalImg(this)" src="img/Pizza Salami.webp" alt="Pizza Salami" title="Pizza Salami">
Pretty hard to read such a long line. When you have so many attributes you can put 1 bellow another.
<img class="image" 
         onmouseover="bigImg(this)"
....etc>

2021-04-12 09:39 UTC, chioreandan commented on style.css
> +.image {
I usually name this kind of classes .image-wrapper

2021-04-12 09:39 UTC, chioreandan commented on style.css
> +.image1 {
This is not a good naming for this class. Avoid using classes and methods like this image1, method1, method3, etc

2021-04-12 09:39 UTC, chioreandan commented on style.css
> +.button2 {
same here, naming

2021-04-12 13:10 UTC, AdrianFlorian requested changes

2021-04-12 13:10 UTC, AdrianFlorian commented on buttonAdd.js
> +  // document.forms[0].reset(); // to clear the form for the next entries
do you need this one? :-)

2021-04-12 13:10 UTC, AdrianFlorian commented on buttonAdd.js
> +//saving to localStorage
why do you need this comment?

2021-04-12 13:10 UTC, AdrianFlorian commented on buttonAdd.js
> +//add a new product
same here, why need the comment? :-)

2021-04-13 07:00 UTC, AdrianFlorian commented
@Sunzi2598 can you please review your own PR and let me know what can be impoved based on the previous comments? :-)

2021-04-13 07:36 UTC, Sunzi2598 commented
I have to change the name for dropdown containers and buttons

2021-04-13 07:37 UTC, Sunzi2598 commented
@AdrianFlorian

2021-04-13 07:38 UTC, AdrianFlorian commented
@Sunzi2598 what about the spacing/newlines? :-)

2021-04-13 12:07 UTC, Sunzi2598 commented
@AdrianFlorian @chioreandan

2021-04-15 06:30 UTC, chioreandan requested changes

2021-04-15 06:30 UTC, chioreandan commented on buttonAdd.js
> +  for (let i = 0; i < data.length; i++) {
Use ``` forEach() ``` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

2021-04-15 06:30 UTC, chioreandan commented on buttonAdd.js
> +};
add empty line

2021-04-15 06:30 UTC, chioreandan commented on index.html
> +                    <li><a href = "#home" >Home</a></li>
@Sunzi2598 you don't need spaces between arguments and value. It should look something like this
 ``` class="main-nav" ```

2021-04-15 06:30 UTC, chioreandan commented on index.html
> +                    <li><a href = "#home" >Home</a></li>
Please apply this change everywhere.

2021-04-15 06:30 UTC, chioreandan commented on index.html
> +  </head>
add empty line after each big section/block

2021-04-15 06:30 UTC, chioreandan commented on slider.js
> +  /* set function vars */
I think anybody that heard of programming knows what this section does. Please remove all your unnecessary comments as @AdrianFlorian said.

2021-04-15 07:31 UTC, Sunzi2598 commented
Can you check again please? @AdrianFlorian @chioreandan

2021-04-15 09:36 UTC, AdrianFlorian commented
@Sunzi2598 https://chris.beams.io/posts/git-commit/ please go through this - it's important to follow those guidelines for the Git commit messages as well as the branching naming conventions :-)

2021-04-15 09:38 UTC, AdrianFlorian approved these changes
👏 nice job Alexandra!

2021-04-15 09:38 UTC, AdrianFlorian commented on buttonAdd.js
> +function addProductToTable() {
nice 👍🏻. Isn't this much nicer, @Sunzi2598 ? :-)

2021-04-19 07:43 UTC, chioreandan approved these changes
Looking good. Try to also change the tab spacing for `index.html` to 2 spaces.

2021-04-19 12:37 UTC, merged